### ISSUE TITLE
Errors when attempting re-analyzation after tweaking settings

### ISSUE THREAD

**Issue by Konkss** [negdo/Sound_Nodes#8]
In Blender 4.0.2
Windows 10
Was testing this out, everything was working great for me until I tried to re-analyze the song I had been using.
I wantedto change settings (like a different smoothing factor) and the after hitting Analyze Audio again, I got errors, then the output of the sound nodes became 0. I tried clearing the nodes, re-initializing the plugin, deleting the keyframes channel. Still got the error codes and the output was 0 even though new keyframes were created

The only way I could get it to work again was to make a new project and freshly analyze a song again.

<img width="873" alt="2024-02-02_19h00_57" src="https://github.com/negdo/Sound_Nodes/assets/54293831/e79cd6dc-35c7-4051-bdd2-7ee3c9262597">

**Comment by negdo** [comment]
The error should now be fixed in the last version. You can download the updated file from Blender Market.
